apps/app1_landingpage/urls.py
# app-level urls.py for Landing Page app:
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),

]

mypython_projects2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include ('apps.app1_landingpage.urls', namespace='app1')),
    url(r'^bright_ideas1/', include ('apps.bright_ideas1.urls', namespace='bright_ideas1')),
    url(r'^bright_ideas2/', include ('apps.bright_ideas2.urls', namespace='bright_ideas2')),
    url(r'^network1/', include ('apps.network1.urls', namespace='network1')),
    url(r'^network2/', include ('apps.network2.urls', namespace='network2')),
    url(r'^playlist1/', include ('apps.playlist1.urls', namespace='playlist1')),
    url(r'^playlist2/', include ('apps.playlist2.urls', namespace='playlist2')),
    url(r'^admin/', admin.site.urls),
]

apps/app1_landingpage/models.py
from django.db import models

# Create your models here.

apps/app1_landingpage/views.py
from django.shortcuts import render, HttpResponse, redirect


def index(request):
    print("This is index method in Landing Page views.py")
    return render(request, 'app1_landingpage/index.html')

    

apps/app1_landingpage/templates/app1_landingpage/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app1_landingpage/css/style.css' %}" media="screen" title="no title">

   <title>Python projects II</title>

   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
    $(document).ready(function() {
        function loop() {
            $('div').css({right:0});
            $('div').animate ({
                right: '+=2090',
            }, 10000, 'linear', function() {
                loop();
            });
        }
        loop();
    });
    </script>
  </head>

  <body>
    <fieldset>
    <legend>PYTHON PROJECTS II</legend>

    <div class = "column">
      <h2>Python projects by Karen S. Welch</h2>
      <p><a href="{% url 'bright_ideas1:index' %}">Bright Ideas</a>Login/register; post your ideas and "like" ideas posted by other users</p>

      <p><a href="{% url 'network1:index' %}">Network</a>Create a networking account; send and accept invitations to and from other networkers</p>

      <p><a href="{% url 'playlist1:index' %}">Playlist</a>Login/register; add songs to site, add songs to your playlist, add other users' songs to your playlist</p>
    </div>
    <p><span style = "color: red">Visitors are invited to log in as hgranger@hogwarts.com, password: studymore</span></p>
  </fieldset>

  <div style="margin-left: 0px; position:absolute"><img src = "static/app1_landingpage/images/mypython4.jpg"></div>
  <div id="grass">
    <p>||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||ll||</p>
  </div>
  <br>
  <div class = "main_link">
    <a href="http://karenwelch.net.s3-website.us-east-2.amazonaws.com">Back to main page</a>
  </div>


</body>
</html>