apps/bright_ideas2/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
# root route to index method
    url(r'^$', views.index, name='index'),
    url(r'^all_likes/(?P<post_id>\d+)$', views.all_likes, name='all_likes'),
    url(r'^users/(?P<user_id>\d+)$', views.users, name='users'),
    url(r'^create_idea$', views.create_idea, name='create_idea'),
    url(r'^like_idea/(?P<post_id>\d+)$', views.like_idea, name='like_idea'),
    url(r'^delete_post/(?P<post_id>\d+)$', views.delete_post, name='delete_post'),
]

apps/network1/urls.py
from django.conf.urls import url, include
from . import views

# This is app_one
urlpatterns = [
# root route to index method
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^logout$', views.logout, name='logout'),

]

mypython_projects2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include ('apps.app1_landingpage.urls', namespace='app1')),
    url(r'^bright_ideas1/', include ('apps.bright_ideas1.urls', namespace='bright_ideas1')),
    url(r'^bright_ideas2/', include ('apps.bright_ideas2.urls', namespace='bright_ideas2')),
    url(r'^network1/', include ('apps.network1.urls', namespace='network1')),
    url(r'^network2/', include ('apps.network2.urls', namespace='network2')),
    url(r'^playlist1/', include ('apps.playlist1.urls', namespace='playlist1')),
    url(r'^playlist2/', include ('apps.playlist2.urls', namespace='playlist2')),
    url(r'^admin/', admin.site.urls),
]

apps/bright_ideas2/models.py
from django.db import models
from ..bright_ideas1.models import *

# Create your models here.
class Idea(models.Model):
    post = models.TextField()
    adds_idea = models.ForeignKey(User, related_name="added_by")
    likes_idea = models.ManyToManyField(User, related_name="liked_by")
    times_liked = models.IntegerField(default=0)

apps/bright_ideas2/views.py
from django.shortcuts import render, HttpResponse, redirect
from ..bright_ideas1.models import User
from .models import Idea
from django.contrib import messages
from django.db.models import Count


# renders index.html
def index(request):
    if 'user_id' not in request.session:
        return redirect('bright_ideas1:index')
    else:
        print("This is index function in bright_ideas2 views.py")
        all_ideas = Idea.objects.all()
        for idea in all_ideas:
            print("Count is:", idea.likes_idea.count())
            idea_count = idea.likes_idea.count()
            if idea_count == 1:
                str_people = "person"
                str_likes = "likes"
            else:
                str_people = "people"
                str_likes = "like"
        context = {
            'all_ideas': all_ideas,
            'str_people': str_people,
            'str_likes': str_likes,
        }
        return render(request, 'bright_ideas2/index.html', context)


# renders likes.html
def all_likes(request, post_id):
    print("This is all_likes function in bright_ideas2 views.py")
    this_idea = Idea.objects.get(id=post_id)
    users_like_idea = User.objects.filter(liked_by=Idea.objects.get(id=post_id))
    context = {
        'idea': this_idea,
        'users': users_like_idea,
    }
    return render(request, 'bright_ideas2/all_likes.html', context)


# renders users.html, with id
# still haven't figured out how to get the total number of user likes
def users(request, user_id):
    print("This is users function in bright_ideas2 views.py")
    this_user = User.objects.get(id=user_id)
    # all Idea objects created by the session user
    this_user_ideas = Idea.objects.filter(adds_idea=this_user)
    likes_count = 0
    for idea in this_user_ideas:
        likes_count = likes_count + idea.times_liked
    context = {
        'user': this_user,
        'likes_count': likes_count,
    }
    return render(request, 'bright_ideas2/users.html', context)


# session user creates an Idea object (post)
def create_idea(request):
    print("This is create_idea function in bright_ideas2 views.py")
    if request.method == 'POST':
        this_post = request.POST['post']
        this_poster = User.objects.get(id=request.session['user_id'])
        this_idea = Idea.objects.create(post=this_post, adds_idea=this_poster)
        print(this_idea.post, this_idea.adds_idea.name)
        return redirect('bright_ideas2:index')
    return redirect('bright_ideas2:index')


# session user likes an Idea object (post)
def like_idea(request, post_id):
    print("This is like_idea function in bright_ideas2 views.py")
    this_user = User.objects.get(id=request.session['user_id'])
    this_idea = Idea.objects.get(id=post_id)
    this_idea.likes_idea.add(this_user)
    # increments like count
    this_idea.times_liked = this_idea.times_liked + 1
    this_idea.save()
    print("Total times idea liked:", this_idea.times_liked)

    return redirect('bright_ideas2:index')


# lets session user delete own posts
def delete_post(request, post_id):
    print("This is delete_post function in bright_ideas2 views.py")
    post_to_delete = Idea.objects.get(id=post_id)
    post_to_delete.delete()
    print(post_to_delete.post, "deleted!")
    return redirect('bright_ideas2:index')

apps/bright_ideas2/templates/bright_ideas2/all_likes.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'bright_ideas2/css/style.css' %}" media="screen" title="no title">
    <title></title>
  </head>

  <body>

    <div class = "header">
      <a href={% url 'bright_ideas2:index' %}>Bright Ideas</a><a href={% url 'bright_ideas1:logout' %}>Log out</a>
    </div>

    <p><a href="{% url 'bright_ideas2:users' user_id=idea.adds_idea.id %}">{{ idea.adds_idea.name }}</a> says: <fieldset>{{ idea.post }}</fieldset>


    <div class = "table1">
    <h3>People who liked this post:</h3>
      <table>
        <thead>
          <tr>
            <th>Alias</a></th>
            <th>Name</th>
          </tr>
        </thead>

        <tbody>
          {% for user in users %}
            <tr>
              <p><td><a href="{% url 'bright_ideas2:users' user_id=user.id %}">{{ user.alias }}</a></td></p>
              <p><td>{{ user.name }}</td></p>
          {% endfor %}
        </tbody>
      </table>
    </div><!-- table1 end div -->
    <br>

  </body>
</html>

apps/bright_ideas2/templates/bright_ideas2/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'bright_ideas2/css/style.css' %}" media="screen" title="no title">
    <title></title>
  </head>

  <body>

    <div class = "header">
    <h1 class="one_line">Hi, {{ request.session.user_alias }}!</h1><a href={% url 'app1:index' %}>Home page</a><a href={% url 'bright_ideas1:logout' %}>Log out</a>
  </div>


  <div class = "form_div">
    <form class="this_form" action="{% url 'bright_ideas2:create_idea' %}" method="POST">
      {% csrf_token %}
        <textarea name = "post" placeholder = "Post your idea here..." rows="1" cols="40%"></textarea>
        <input type="Submit" value="Post idea!">
    </form>
  </div>

  <div class="ideabox">
    {% for idea in all_ideas %}
      <p><a href="{% url 'bright_ideas2:users' user_id=idea.adds_idea.id %}">{{ idea.adds_idea.name }}</a> says:<fieldset>{{ idea.post }}</fieldset></p>
      <p><a href="{% url 'bright_ideas2:like_idea' post_id=idea.id %}">Like</a><a href="{% url 'bright_ideas2:all_likes' post_id=idea.id %}">{{ idea.likes_idea.count }}  {{ str_people }}</a> {{ str_likes }} this</p>

      {% if idea.adds_idea.id == request.session.user_id %}
        <p><a href="{% url 'bright_ideas2:delete_post' post_id=idea.id %}">Delete this Post</a></p>
      {% endif %}
      <h6>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</h6>
    {% endfor %}
  </div>

  </body>
</html>

apps/bright_ideas2/templates/bright_ideas2/users.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'bright_ideas2/css/style.css' %}" media="screen" title="no title">
    <title></title>
  </head>

  <body>

    <div class = "header">
      <a href={% url 'bright_ideas2:index' %}>Bright Ideas</a><a href={% url 'bright_ideas1:logout' %}>Log out</a>
    </div>

    <h3>Name: {{ user.name }}</h3>
    <h3>Alias: {{ user.alias }}</h3>
    <h3>Email: {{ user.email }}</h3>


    <h3>Total Number of Posts: {{ user.added_by.count }} </h3>
    <h3>Total Number of Likes: {{ likes_count }} </h3>

  </body>
</html>