apps/network1/urls.py
from django.conf.urls import url, include
from . import views

# This is app_one
urlpatterns = [
# root route to index method
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^logout$', views.logout, name='logout'),

]

apps/playlist2/urls.py
from django.conf.urls import url, include
from . import views

# This is app_two
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^songs/(?P<song_id>\d+)$', views.songs, name='songs'),
    url(r'^create_song$', views.create_song, name='create_song'),
    url(r'^add_to_playlist/(?P<song_id>\d+)$', views.add_to_playlist, name='add_to_playlist'),
    url(r'^users/(?P<user_id>\d+)$', views.users, name='users'),

]

mypython_projects2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include ('apps.app1_landingpage.urls', namespace='app1')),
    url(r'^bright_ideas1/', include ('apps.bright_ideas1.urls', namespace='bright_ideas1')),
    url(r'^bright_ideas2/', include ('apps.bright_ideas2.urls', namespace='bright_ideas2')),
    url(r'^network1/', include ('apps.network1.urls', namespace='network1')),
    url(r'^network2/', include ('apps.network2.urls', namespace='network2')),
    url(r'^playlist1/', include ('apps.playlist1.urls', namespace='playlist1')),
    url(r'^playlist2/', include ('apps.playlist2.urls', namespace='playlist2')),
    url(r'^admin/', admin.site.urls),
]

apps/playlist2/models.py
from django.db import models
from ..playlist1.models import *

class Song(models.Model):
    title=models.CharField(max_length=100)
    artist=models.CharField(max_length=100)
    # many songs, many users
    added_by=models.ManyToManyField(User, related_name="added")
    # total number of times a song has been added
    times_added = models.IntegerField(default=0, null=True, blank=True)


class AddtoPlaylist(models.Model):
    # many counts per user
    user_link = models.ForeignKey(User, related_name="links_user", null=True, blank=True)
    # many counts per song
    song_link = models.ForeignKey(Song, related_name="links_song", null=True, blank=True)
    # number of times each user adds a song
    times_added = models.IntegerField(default=0, null=True, blank=True)

apps/playlist2/views.py
from django.shortcuts import render, HttpResponse, redirect
from ..playlist1.models import User
from .models import *
from django.contrib import messages


# renders index.html (dashboard)
def index(request):
    if 'user_id' not in request.session:
        return redirect('playlist1:index')
    else:
        print("This is index function in playlist2 views.py")

        context = {
            'playlist': Song.objects.all()
        }
        return render(request, 'playlist2/index.html', context)


# renders songs.html
def songs(request, song_id):
    print("This is songs function in playlist2 views.py")
    this_song = Song.objects.get(id=song_id)
    # song_users = User.objects.filter(added=this_song)
    this_song_added = AddtoPlaylist.objects.filter(song_link=this_song)
    context = {
        'song': this_song,
        'song_added': this_song_added,
    }
    return render(request, 'playlist2/songs.html', context)


# creates a new Song object from form data
def create_song(request):
    print("This is create_song function in playlist2 views.py")
    if request.method == 'POST':
        print("method=POST")
        this_title = request.POST['title']
        this_artist = request.POST['artist']
        print(this_title, this_artist)
# song validations
# checks for blank form field / field length
        if len(this_title) == 0 or len(this_artist) == 0:
            print("Please fill out the form field")
            messages.warning(request, "Form fields must not be left blank")
            return redirect('playlist2:create_song')
        if len(this_title) < 2 or len(this_artist) == 0:
            print("Song title/artist must have at least 2 characters")
            messages.warning(request, "Item must have at least 2 characters")
            return redirect('playlist2:create_song')
# validations passed; creates song
        # print("Ready to create song")
        this_song = Song.objects.create(title=this_title, artist=this_artist)
        return redirect('playlist2:index')

    return redirect('playlist2:index')


# adds a song to session user's playlist
# increases count of times song added
def add_to_playlist(request, song_id):
    print("This is add_to_playlist function in playlist2 views.py")
    this_song = Song.objects.get(id=song_id)
    user_id = request.session['user_id']
    this_user = User.objects.get(id=user_id)
    this_song.added_by.add(this_user)

# song counter, total adds
    this_song.times_added = this_song.times_added + 1
    this_song.save()
    print("Total times song added:", this_song.times_added)

# song count by user
# checks whether an AddtoPlaylist object exists for session user and selected song
    user_adds_song = AddtoPlaylist.objects.filter(user_link=this_user).filter(song_link=this_song)
# checks how many times user has added this song
    this_add_count = user_adds_song.count()
    print(this_user, "has added this song", this_add_count, "times")

    if this_add_count == 0: # if session user has never added this song to their playlist
        print("IF")
        # creates an AddtoPlaylist object for session user and this song
        this_add = AddtoPlaylist.objects.create(user_link=this_user, song_link=this_song, times_added=1)
        print(this_add.user_link.first_name, "created an AddtoPlaylist object for", this_add.song_link.title)

    else: # if session user has added this song to their playlist before
        print("ELSE")
        # fetches to AddtoPlaylist object for updating
        this_add = AddtoPlaylist.objects.filter(user_link=this_user).get(song_link=this_song)
        this_add.times_added = this_add.times_added + 1 # increments the count
        this_add.save()
        print(this_add.user_link.first_name, "has added", this_add.song_link.title, this_add.times_added, "times")

    return redirect('playlist2:index')


# renders users.html
def users(request, user_id):
    print("This is users function in playlist2 views.py")
    this_user = User.objects.get(id=user_id)
    # user_added_songs = Song.objects.filter(added_by=this_user)
    context = {
        'user': this_user,
        'playlist': AddtoPlaylist.objects.filter(user_link=this_user),
    }
    return render(request, 'playlist2/users.html', context)

apps/playlist2/templates/playlist2/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'playlist2/css/style.css' %}" media="screen" title="no title">
    <title>Index</title>
  </head>

  <body>

    <div class = "header">
      <h1 class="one_line">Hello, {{ request.session.user_first_name }}!</h1><a href={% url 'playlist1:logout' %}>Log out</a>
    </div>

    <div class = "table1">
    <h3>All the songs in our hub:</h3>
      <table>
        <thead>
          <tr>
            <th>Artist</a></th>
            <th>Title</th>
            <th>No. of Times Song Has Been Added</th>
            <th>Add to Playlist</th>
          </tr>
        </thead>

        <tbody>
          {% for song in playlist %}
            <tr>
              <p><td>{{ song.artist }}</td></p>
              <p><td><a href="{% url 'playlist2:songs' song_id=song.id %}">{{ song.title }}</a></td></p>
              <p><td>{{ song.times_added }}</td></p>
              <p><td><a href="{% url 'playlist2:add_to_playlist' song_id=song.id %}">Add<a></td></p>
          {% endfor %}
        </tbody>
      </table>
    </div><!-- table1 end div -->
    <br>

    <div class = "form_div">
      <h3>Create a New Wish List Item</h3>
      <form class="songs_form" action="{% url 'playlist2:create_song' %}" method="POST">
        {% csrf_token %}
        <h3>Add a Song:</h3>
          <p>Title: <input type="text" name="title" value=""></p>
          <p>Artist: <input type="text" name="artist" value=""></p>
          <input type="Submit" value="Add Song">
      </form>
    </div>

    <div class="error_messages">
  <!-- displaying error messages -->
        {% if messages %}
          <ul class="messages">
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

  </body>
</html>

apps/playlist2/templates/playlist2/songs.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'playlist2/css/style.css' %}" media="screen" title="no title">

    <title>Songs</title>
  </head>

  <body>

    <div class="header">
      <a href={% url 'playlist2:index' %}>Dashboard</a><a href={% url 'playlist1:logout' %}>Log out</a>
    </div>

    <div class = "table2">
    <h3>Others who added {{ song.artist }} - {{ song.title }}</h3>
      <table>
        <thead>
          <tr>
            <th>Name</a></th>
            <th>Times Added</th>
            </tr>
        </thead>

        <tbody>
          <!-- song_added is AddtoPlaylist objects -->
          {% for adds in song_added %}
            <tr>
              <p><td><a href="{% url 'playlist2:users' user_id=adds.user_link.id %}">{{ adds.user_link.first_name }} {{ adds.user_link.last_name }}</a></td></p>
              <p><td>{{ adds.times_added }}</td></p>
          {% endfor %}
        </tbody>
      </table>
    </div><!-- table1 end div -->

  </body>
</html>

apps/playlist2/templates/playlist2/users.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'playlist2/css/style.css' %}" media="screen" title="no title">
    <title>Users</title>
  </head>

  <body>

    <div class="header">
      <a href={% url 'playlist2:index' %}>Dashboard</a><a href={% url 'playlist1:logout' %}>Log out</a>
    </div>

    <div class = "table3">
    <h3>{{ user.first_name }} {{ user.last_name }}'s playlist</h3>
      <table>
        <thead>
          <tr>
            <th>Artist</a></th>
            <th>Title</th>
            <th>Times Added</th>
          </tr>
        </thead>

        <tbody>
          <!-- AddtoPlaylist objects -->
          {% for adds in playlist %}
            <tr>
              <p><td>{{ adds.song_link.artist }}</td></p>
              <p><td>{{ adds.song_link.title }}</a></td></p>
              <p><td>{{ adds.times_added }}</td></p>
              {% endfor %}
        </tbody>
      </table>
    </div><!-- table3 end div -->
    <br>



  </body>
</html>